name = "cam-duc-hiep-test"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "cam-duc-hiep-db-test"
database_id = "32b66373-645f-43a9-88d2-c554adb4bf09"
